
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: tasks
    container_name: task-mysql
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: